SELECT EMP_NUM, EMP_FNAME, EMP_LNAME, EMP_INITIAL FROM EMPLOYEE WHERE EMP_LNAME LIKE 'Smith%' ORDER BY EMP_NUM;

SELECT PROJ_NAME,PROJ_VALUE, PROJ_BALANCE, EMP_LNAME, EMP_FNAME, EMP_INITIAL, JOB.JOB_CODE, JOB.JOB_DESCRIPTION, JOB.JOB_CHG_HOUR 
FROM EMPLOYEE JOIN PROJECT ON PROJECT.EMP_NUM = EMPLOYEE.EMP_NUM JOIN JOB ON JOB.JOB_CODE = EMPLOYEE.JOB_CODE ORDER BY PROJ_VALUE;

SELECT ASSIGN_NUM, EMP_NUM, PROJ_NUM, ASSIGN_CHARGE, CONVERT(ASSIGN_CHG_HR*ASSIGN_HOURS, DECIMAL(7,2)) AS VALIDATION
 FROM ASSIGNMENT ORDER BY ASSIGN_NUM;
 
 SELECT EMPLOYEE.EMP_NUM, EMP_LNAME, CONVERT(SUM(ASSIGN_HOURS), DECIMAL(7,2)) AS SUMOFASSIGNHRS, 
 CONVERT(SUM(ASSIGN_CHARGE), DECIMAL(7,2)) AS SUMOFASSIGNCHARGE FROM ASSIGNMENT 
 JOIN EMPLOYEE ON ASSIGNMENT.EMP_NUM = EMPLOYEE.EMP_NUM 
 GROUP BY EMP_NUM ORDER BY EMP_NUM

