SELECT COUNT(CUS_BALANCE) FROM CUSTOMER WHERE CUS_BALANCE > 500;

SELECT CUS_CODE, INVOICE.INV_NUMBER, P_DESCRIPT, LINE_UNITS, LINE_PRICE FROM INVOICE 
JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER 
JOIN PRODUCT ON PRODUCT.P_CODE = LINE.P_CODE 
ORDER BY CUS_CODE, INVOICE.INV_NUMBER, P_DESCRIPT;

SELECT CUSTOMER.CUS_CODE, CUS_BALANCE, SUM(LINE_UNITS*LINE_PRICE) AS TOTAL_PURCHASES, 
COUNT(LINE_NUMBER) AS NUM_PURCHASES, AVG(LINE_UNITS*LINE_PRICE) AS AVG_PURCHASE_AMT FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
GROUP BY CUSTOMER.CUS_CODE
ORDER BY CUSTOMER.CUS_CODE;

SELECT SUM(TOTAL_INVOICES), SUM(TOT_PURCH) AS TOTAL_SALES, 
MIN(TOT_PURCH) AS MIN_CUS_PURCH, MAX(TOT_PURCH) AS MAX_CUS_PURCH, AVG(TOT_PURCH) AS AVG_CUS_PURCH 
FROM (SELECT CUS_CODE, COUNT(DISTINCT INVOICE.INV_NUMBER) AS TOTAL_INVOICES,
		CONVERT(SUM(LINE_UNITS*LINE_PRICE), DECIMAL(7,2)) AS TOT_PURCH FROM INVOICE 
		JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER GROUP BY CUS_CODE) AS TOTS;
        
SELECT SUM(CUS_BALANCE) AS TOT_BALANCE, MIN(CUS_BALANCE) AS MIN_BALANCE, MAX(CUS_BALANCE) AS MAX_BALANCE,
AVG(CUS_BALANCE) AS AVG_BALANCEemployeeemployee FROM CUSTOMER;