SET SQL_SAFE_UPDATES = 0;

CREATE TABLE `MEMBERSHIP` (
  `MEM_NUM` int NOT NULL,
  `MEM_FNAME` varchar(255),
  `MEM_LNAME` varchar(255),
  `MEM_STREET` varchar(255),
  `MEM_CITY` varchar(255),
  `MEM_STATE` varchar(255),
  `MEM_ZIP` int,
  `MEM_BALANCE` float,
  PRIMARY KEY (`MEM_NUM`)
);

CREATE TABLE `RENTAL` (
	`RENT_NUM` INT NOT NULL,
    `RENT_DATE` DATE,
    `MEM_NUM` INT,
	PRIMARY KEY (`RENT_NUM`),
    FOREIGN KEY (`MEM_NUM`) REFERENCES `MEMBERSHIP` (`MEM_NUM`)
);