SELECT BOOK_TITLE, BOOK_COST, BOOK_YEAR FROM BOOK WHERE BOOK_YEAR > 2015 ORDER BY BOOK_TITLE;

SELECT BOOK_NUM, BOOK_TITLE, BOOK_SUBJECT, BOOK_COST FROM BOOK 
WHERE ((BOOK_SUBJECT = 'Middleware' OR BOOK_SUBJECT = 'Cloud') AND BOOK_COST > 70) 
ORDER BY BOOK_NUM;

SELECT BOOK_SUBJECT, COUNT(BOOK_NUM) FROM BOOK GROUP BY BOOK_SUBJECT ORDER BY COUNT(BOOK_NUM) DESC, BOOK_SUBJECT;

SELECT AUTHOR.AU_ID, AU_FNAME, AU_LNAME, BOOK.BOOK_NUM, BOOK_TITLE FROM BOOK 
JOIN WRITES ON BOOK.BOOK_NUM = WRITES.BOOK_NUM JOIN AUTHOR ON WRITES.AU_ID = AUTHOR.AU_ID 
WHERE BOOK_SUBJECT = 'Cloud' ORDER BY BOOK_TITLE, AU_LNAME;

SELECT BOOK.BOOK_NUM, BOOK_TITLE, COUNT(CHECK_NUM) AS 'Times Checked Out' FROM BOOK 
JOIN CHECKOUT ON BOOK.BOOK_NUM = CHECKOUT.BOOK_NUM 
GROUP BY BOOK.BOOK_NUM HAVING (COUNT(CHECK_NUM) > 5) ORDER BY COUNT(CHECK_NUM) DESC, BOOK_TITLE;

SELECT BOOK_NUM, BOOK_TITLE, BOOK_COST FROM BOOK WHERE BOOK_COST = (SELECT MIN(BOOK_COST) FROM BOOK) ORDER BY BOOK_NUM;

SELECT AUTHOR.AU_ID, AU_FNAME, AU_LNAME FROM AUTHOR 
WHERE AUTHOR.AU_ID NOT IN (SELECT AUTHOR.AU_ID FROM AUTHOR JOIN WRITES ON AUTHOR.AU_ID = WRITES.AU_ID 
							JOIN BOOK ON WRITES.BOOK_NUM = BOOK.BOOK_NUM WHERE BOOK.BOOK_SUBJECT = 'Programming') 
GROUP BY AUTHOR.AU_ID ORDER BY AU_LNAME;
