CREATE USER tester1;
GRANT ALL PRIVILEGES ON *.* TO tester1 WITH GRANT OPTION;
SET PASSWORD FOR tester1 = 'tester1password';

REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'tester1';

SELECT CURRENT_USER();
SELECT * FROM colleges;

SHOW GRANTS FOR tester1;

